version: "3.9"

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    # Sem porta exposta conforme solicitado
    # ports:
    #   - "6379:6379"
    command: ${REDIS_COMMAND:-redis-server --appendonly yes}
    volumes:
      - ${REDIS_DATA_VOLUME:-redis_data}:/data
    networks:
      - ${NETWORK_NAME:-ross-network}

volumes:
  redis_data:

networks:
  ross-network:
    external: true
