<?php
require_once("./App/Views/layouts/main.php");
require_once('./logs.php');
?>
<!doctype html>
<html lang="pt-Br">
<head>
    <?php includeFileWithVariables('./App/Views/layouts/title-meta.phtml', array('title' => 'Dashboard')); ?>
    <!-- CSS -->
    <?php require_once './App/Views/layouts/head-css.phtml'; ?>
</head>
<body>

    <div class="d-flex main-container">
        <!-- =============================================== -->
        <!-- Barra Lateral (Sidebar) para DESKTOP -->
        <!-- =============================================== -->
        <aside class="sidebar d-none d-md-flex flex-column">
            <!-- Logo -->
            <div class="logo-container d-flex align-items-center mb-5">
                <div class="logo-placeholder me-3">
                    <span>RS</span>
                </div>
                <div>
                    <h1 class="logo-title mb-0">ROSS</h1>
                    <p class="logo-subtitle mb-0">Analista Jurídico</p>
                </div>
            </div>
            <!-- Navegação -->
            <div class="sidebar-nav-container">
                <!-- Navegação Principal -->
                <nav class="sidebar-nav nav flex-column">
                    <a class="nav-link <?= ($this->view->active_page ?? '') == 'home' ? 'active' : '' ?>" href="/home">
                        <i class="bi bi-layout-text-sidebar-reverse me-2"></i> Dashboard
                    </a>
                    <a class="nav-link <?= ($this->view->active_page ?? '') == 'contratos' ? 'active' : '' ?>" href="/contratos">
                        <i class="bi bi-file-earmark-text me-2"></i> Contratos
                    </a>
                    <!-- <a class="nav-link" href="#">
                        <i class="bi bi-gear me-2"></i> Configurações
                    </a> -->
                    <a class="nav-link <?= ($this->view->active_page ?? '') == 'minha_conta' ? 'active' : '' ?>" href="/minha_conta">
                        <i class="bi bi-person me-2"></i> Minha Conta
                    </a>
                </nav>

                <!-- Botão de Sair -->
                <div class="mt-auto">
                    <a class="nav-link logout-link" href="/sair">
                        <i class="bi bi-box-arrow-left me-2"></i> Sair
                    </a>
                </div>

            </div>
        </aside>

        <?php print_r($this->content()); ?>
        
    </div>

    <!-- =============================================== -->
    <!-- Offcanvas para MOBILE -->
    <!-- =============================================== -->
    <div class="offcanvas offcanvas-start d-md-none mobile-offcanvas" tabindex="-1" id="mobileMenu">
      <div class="offcanvas-header">
        <div class="logo-container d-flex align-items-center">
            <div class="logo-placeholder me-3">
                <span>RS</span>
            </div>
            <div>
                <h1 class="logo-title mb-0">ROSS</h1>
                <p class="logo-subtitle mb-0">Analista Jurídico</p>
            </div>
        </div>
        <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
      <div class="offcanvas-body d-flex flex-column p-4">
        <!-- Navegação Mobile -->
        <nav class="nav flex-column sidebar-nav">
            <a class="nav-link <?= ($this->view->active_page ?? '') == 'home' ? 'active' : '' ?>" href="/home">
                <i class="bi bi-layout-text-sidebar-reverse me-2"></i>
                Dashboard
            </a>
            <a class="nav-link <?= ($this->view->active_page ?? '') == 'contratos' ? 'active' : '' ?>" href="/contratos">
                <i class="bi bi-file-earmark-text me-2"></i>
                Contratos
            </a>
            <!-- <a class="nav-link" href="#">
                <i class="bi bi-gear me-2"></i>
                Configurações
            </a> -->
            <a class="nav-link <?= ($this->view->active_page ?? '') == 'minha_conta' ? 'active' : '' ?>" href="/minha_conta">
                <i class="bi bi-person me-2"></i>
                Minha Conta
            </a>
        </nav>

         <!-- Botão de Sair no final do offcanvas -->
         <div class="mt-auto">
            <a class="nav-link logout-link" href="/sair">
                <i class="bi bi-box-arrow-left me-2"></i> Sair
            </a>
        </div>
    </div>


    <!-- JS -->
    <?php require_once './App/Views/layouts/footer-js.phtml'; ?>

    <!-- Page Specific JS -->
    <?php $this->renderSection('scripts'); ?>

</body>
</html>
