<footer class="footer bg-dark text-white pb-2 pt-2 border-top">
    <div class="container-fluid">
        <div class="row">
            <div class="col-sm-6">
                <script>document.write(new Date().getFullYear())</script> © Renata - PHP Template.
            </div>
            <div class="col-sm-6">
                <div class="text-sm-end d-none d-sm-block">
                   Design By Luis Oliveira
                </div>
            </div>
        </div>
    </div>
</footer>