   <!-- Required meta tags -->
   <meta charset="utf-8" />
   <title><?= ($title) ? $title : '' ?> | Template PHP MVC</title>
   <link rel="shortcut icon" href="./Assets/images/favicon.ico" type="image/x-icon">
   <!-- SEO -->
   <meta name="description" content="Renata o template MVC para php 8.2, Facilitando o inicio do seu projeto por que tempo é dinheiro ">
   <!-- Breve descrição do conteúdo do site -->
   <meta name="keywords" content="PHP, MVC, Template PHP, Ferramenta PHP, Luis Oliveira, Gu00col, Outraforma, Outra Forma, Agência Outra Forma, Luis Gustavo Barbosa de Oliveira, Desenvolvimento, Aprendendo a programar">
   <!-- Palavras-chave relevantes para SEO -->
   <meta name="author" content="Luis Gustavo Barbosa de Oliveira">
   <meta
       name="viewport"
       content="width=device-width, initial-scale=1, shrink-to-fit=no" />