<header class="bg-primary sticky-top border-bottom">
<nav
            class="navbar navbar-expand-sm navbar-dark bg-dark"
        >
            <div class="container">
                <a class="navbar-brand" href="/"><img src="./Assets/images/logo.png" width="25" alt="Logo Renata">Renata PHP template</a>
                <button
                    class="navbar-toggler d-lg-none"
                    type="button"
                    data-bs-toggle="collapse"
                    data-bs-target="#collapsibleNavId"
                    aria-controls="collapsibleNavId"
                    aria-expanded="false"
                    aria-label="Toggle navigation"
                >
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="collapsibleNavId">
                    <ul class="navbar-nav ms-auto mt-2 mt-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" href="https://www.linkedin.com/in/luis-g-b-oliveira" aria-current="page"
                                >Linkedin
                                <span class="visually-hidden">(Linkedin)</span></a
                            >
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://outraforma.com.br" aria-current="page"
                                >Outra Forma
                                <span class="visually-hidden">(Outra Forma)</span></a
                            >
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="https://github.com/gu00col/renata_mcv_php_template" aria-current="page"
                                >Repositório 
                                <span class="visually-hidden">(Github)</span></a
                            >
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        
        </header>

       